### PR TITLE
bugfix: remove X relative offset from Y position calculation

### PR DESCRIPTION
**Pull request by mr-salty**
This change is [Reviewable](https://reviewable.io/reviews/dosmanak/wmsavior/1)

### CODE REVIEW

**Comment by mr-salty** [comment]
An aside - thanks so much for this script, now that I'm WFH I was having this problem with the external display constantly.

I made some changes [here](https://github.com/mr-salty/wmsavior/blob/dev/wmsavior.sh), it's still a WIP and needs to be cleaned up, and obviously it's a lot more complicated, but if you're interested I can split up some of the changes and send PRs.

The main thing I wanted to accomplish was running it from cron (which I do every minute), so if the windows all get moved around, I can find the proper backup and restore it. So, it saves to a new file every time it runs, except if all the positions are the same it won't make a new file.  Then, when things get wonky I run `wmsavior show` which lists of all the files in reverse chronological order, with a count of differences from the next newer file, i.e.:

```
$ wmsavior show
-rw-r--r-- 1 salty primarygroup 2586 May 29 19:32 saved.wmctrl.1590795121 0
-rw-r--r-- 1 salty primarygroup 2592 May 29 18:53 saved.wmctrl.1590792781 24
-rw-r--r-- 1 salty primarygroup 2883 May 29 18:41 saved.wmctrl.1590792061 1
-rw-r--r-- 1 salty primarygroup 2804 May 29 17:34 saved.wmctrl.1590788041 2
-rw-r--r-- 1 salty primarygroup 2721 May 29 16:27 saved.wmctrl.1590784021 2
```

The `24` on the second line means that 24 windows moved between it (saved.wmctrl.1590792781) and the newer file (saved.wmctrl.1590795121). that's likely the one I want to restore, so I run `wmsavior restore saved.wmctrl.1590792781`).  I'd like to give it an "auto" mode that tries to figure it out (it doesn't delete anything so if it gets it wrong you could pick another file manually), but I haven't gotten around to it yet (or having it automatically clean up - although that risks losing the "good" file if it gets it wrong, so for now you have to run `wmsavior cleanup` manually)

**Comment by dosmanak** [comment]
Thank you for your contribution. It is really a bug.
 I could not find a solution, how to make the script work correct, so I added the offset 15px. When I apply your change I would have to add another few pixels.
What is your desktop environment?
Have you also removed hardwired 15px or does the script work properly?
I do not have experiences with window managers so I can't properly evaluate all the values I got from `wmctrl -l -G` and `xwininfo -id $id`.

**Comment by mr-salty** [comment]
Ha, you are at least as much of an expert as I am ;)  One would hope there was a way to get the "correct" values but I don't know what it is.

I actually didn't notice the small offsets at first, but there was one window in particular that would always end up with a very negative Y coordinate and mostly off the screen (due to the issue in this PR - I'm not sure why it only affected that one window that badly). So, I decided to try to figure that out, and while doing save/restore back-to-back I saw some of my windows would move down and some would move up by a small amount. Some would also move to the right a bit.  What I discovered was:

* for my window manager (also cinnamon, but maybe it depends on your theme and/or or screen resolution), the Y offset was 29 rather than 15. I also had a 1 pixel X offset.
* **but** after I fixed that, some windows would still move up. I realized they were all Chrome windows - probably because I have "use system title bar and borders" off.  So I special case those and don't apply any offset.

finally, I could run save/restore repeatedly with no windows moving.  The [code is here](https://github.com/mr-salty/wmsavior/blob/0925f1728b45f51b2cd5cd0645a16e788e5066fa/wmsavior.sh#L47-L56) although obviously it's pretty specific to my own environment, which is unfortunate... it would be nice to just get the "right" values.  You *could* have it detect the proper offset by doing the equivalent of save/restore/save for a window and computing the difference in position... but figuring out which windows to special-case would be messy at best (my current method is pretty hacky and probably leaves some things out)

**Comment by dosmanak** [comment]
I am going to accept the bugfix. I will also prepare some better way how to define WM specific offsets.

**Comment by dosmanak** [comment]
FYI I pushed env variables for custom offsets. I see you have many custom modifications, so perhaps it won't be beneficial for you.

**Pull request merged**
